### ISSUE TITLE
Having to set output fluid in ME Fluid Interface after every server reboot

### ISSUE THREAD

**Issue by ReneM** [M3gaFr3ak/ExtraCells2#145]
As per topic, whenever the server have rebooted all my ME Fluid Interfaces have reset, so I need to visit them and set which fluid to output to which side again.

I'm currently running ExtraCells-1.7.10-2.2.22b42 with appliedenergistics2-rv2-beta-1.

I'm guessing the problem is related to this entry that pops up in the fml-server.log (at the very end of the loading, it would seem):
`
[18:49:51] [Server thread/ERROR] [FML/]: A TileEntity tileEntityFluidInterface(extracells.tileentity.TileEntityFluidInterface) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
	at appeng.api.util.DimensionalCoord.<init>(DimensionalCoord.java:47) ~[DimensionalCoord.class:?]
	at extracells.tileentity.TileEntityFluidInterface.getLocation(TileEntityFluidInterface.java:195) ~[TileEntityFluidInterface.class:?]
	at extracells.gridblock.ECFluidGridBlock.getLocation(ECFluidGridBlock.java:47) ~[ECFluidGridBlock.class:?]
	at appeng.me.GridNode.FindConnections(GridNode.java:359) ~[GridNode.class:?]
	at appeng.me.GridNode.updateState(GridNode.java:207) ~[GridNode.class:?]
	at extracells.tileentity.TileEntityFluidInterface.getGridNode(TileEntityFluidInterface.java:87) ~[TileEntityFluidInterface.class:?]
	at extracells.tileentity.TileEntityFluidInterface.func_145839_a(TileEntityFluidInterface.java:312) ~[TileEntityFluidInterface.class:?]
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
`

If you need any other logs/details, let me know :)

**Comment by DrummerMC** [comment]
Fixed

**Comment by ghost** [comment]
it seams that this problem still exist the fluid is still present in the me controller but the system doesnt care what is specified and pumps what ever comes along
ExtraCells-1.7.10-2.1.37b65 and 63 befor hand
appliedenergistics2-rv1-stable-1

(`)
[Server thread/ERROR] [FML/]: A TileEntity tileEntityFluidCrafter(extracells.tileentity.TileEntityFluidCrafter) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at appeng.api.util.DimensionalCoord.<init>(DimensionalCoord.java:24) ~[DimensionalCoord.class:?]
    at extracells.tileentity.TileEntityFluidCrafter.getLocation(TileEntityFluidCrafter.java:111) ~[TileEntityFluidCrafter.class:?]
    at extracells.gridblock.ECFluidGridBlock.getLocation(ECFluidGridBlock.java:47) ~[ECFluidGridBlock.class:?]
    at appeng.me.GridNode.FindConnections(GridNode.java:241) ~[GridNode.class:?]
    at appeng.me.GridNode.updateState(GridNode.java:147) ~[GridNode.class:?]
    at extracells.tileentity.TileEntityFluidCrafter.getGridNode(TileEntityFluidCrafter.java:91) ~[TileEntityFluidCrafter.class:?]
    at extracells.tileentity.TileEntityFluidCrafter.getGridNode(TileEntityFluidCrafter.java:115) ~[TileEntityFluidCrafter.class:?]
    at extracells.tileentity.TileEntityFluidCrafter.func_145839_a(TileEntityFluidCrafter.java:206) ~[TileEntityFluidCrafter.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
    at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
    at mcp.mobius.mobiuscore.monitors.MonitoredTileList.removeCount(MonitoredTileList.java:49) [MonitoredTileList.class:?]
    at mcp.mobius.mobiuscore.monitors.MonitoredList.removeAll(MonitoredList.java:63) [MonitoredList.class:?]
    at fastcraft.a.m.a(F:24) [fastcraft-1.19.jar:?]
    at fastcraft.Hooks.n(F:119) [fastcraft-1.19.jar:?]
    at net.minecraft.world.World.func_72939_s(World.java:1981) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
(`)
